from pybrain2.rl.environments.twoplayergames.gomokuplayers.randomplayer import RandomGomokuPlayer
from pybrain2.rl.environments.twoplayergames.gomokuplayers.killing import KillingGomokuPlayer
from pybrain2.rl.environments.twoplayergames.gomokuplayers.moduledecision import ModuleDecidingPlayer