from pybrain2.rl.environments.twoplayergames.capturegameplayers.randomplayer import RandomCapturePlayer
from pybrain2.rl.environments.twoplayergames.capturegameplayers.killing import KillingPlayer
from pybrain2.rl.environments.twoplayergames.capturegameplayers.nonsuicide import NonSuicidePlayer
from pybrain2.rl.environments.twoplayergames.capturegameplayers.moduledecision import ModuleDecidingPlayer
from pybrain2.rl.environments.twoplayergames.capturegameplayers.clientwrapper import ClientCapturePlayer